name: Packages

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian:unstable
          - debian:trixie
          - debian:bookworm
          - debian:bullseye
          - ubuntu:noble
          - ubuntu:jammy
          - ubuntu:focal
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # Determine which PPA we should upload to
      - name: PPA
        id: ppa
        run: |
          if [[ $REF == refs/tags* ]]
          then
            echo "::set-output name=ppa::kiwixteam/release"
          else
            echo "::set-output name=ppa::kiwixteam/dev"
          fi
        env:
          REF: ${{ github.ref }}

      - uses: legoktm/gh-action-auto-dch@25c8bd09c86c5cce962ad431d076ab1508b3e73f # 2024.07.13
        with:
          fullname: Kiwix builder
          email: release+launchpad@kiwix.org
          distro: ${{ matrix.distro }}

      - uses: legoktm/gh-action-build-deb@test
        if: startswith(matrix.distro, 'debian:')
        name: Build package for ${{ matrix.distro }}
        with:
          distro: ${{ matrix.distro }}
          args: --no-sign

      - uses: legoktm/gh-action-build-deb@test
        if: startswith(matrix.distro, 'ubuntu:')
        name: Build package for ${{ matrix.distro }}
        with:
          args: --no-sign
          ppa: ${{ steps.ppa.outputs.ppa }}

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: Packages for ${{ matrix.distro }}
          path: output

      - uses: legoktm/gh-action-dput@86555e0a81896bcd90536850f388e275eed5fabe # 2024.07.12
        name: Upload dev package
        # Only upload on pushes to main
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && startswith(matrix.distro, 'ubuntu-')
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:kiwixteam/dev
          packages: output/*_source.changes

      - uses: legoktm/gh-action-dput@86555e0a81896bcd90536850f388e275eed5fabe # 2024.07.12
        name: Upload release package
        if: github.event_name == 'release' && startswith(matrix.distro, 'ubuntu-')
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:kiwixteam/release
          packages: output/*_source.changes
